name: 'Deploy to PROD server'
description: 'Deploys to the PROD server'

inputs:
  prod_ssh_private_key:
    description: 'SSH private key for PROD server'
    required: true
  prod_host:
    description: 'SSH host'
    required: true
  prod_user:
    description: 'SSH user'
    required: true
  prod_base_path:
    description: 'Base path on the PROD server'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ inputs.prod_ssh_private_key }}
        HOST: ${{ inputs.prod_host }}
        USER: ${{ inputs.prod_user }}
        BASE_PATH: ${{ inputs.prod_base_path }}
      run: |
        set -e  # Прерывание при ошибке
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        ssh -i private_key.pem $USER@$HOST "mkdir -p $BASE_PATH/assets/ $BASE_PATH/css/ $BASE_PATH/js/" || { echo "SSH command failed"; exit 1; }

        rsync -avz --delete -e "ssh -i private_key.pem" ./public/assets/ $USER@$HOST:$BASE_PATH/assets/ || { echo "Rsync О ASSETS command failed"; exit 1; }
        rsync -avz --delete -e "ssh -i private_key.pem" ./public/css/ $USER@$HOST:$BASE_PATH/css/ || { echo "Rsync О CSS command failed"; exit 1; }
        rsync -avz --delete -e "ssh -i private_key.pem" ./public/js/ $USER@$HOST:$BASE_PATH/js/ || { echo "Rsync О JS command failed"; exit 1; }

        rm private_key.pem  # Удаление временного файла
