name: Deploy to Html

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to HTML server
        uses: ./.github/actions/send-to-dev-html
        with:
          dev_ssh_private_key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          html_project_folder: ${{ secrets.HTML_PROJECT_FOLDER }}
